### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by cjohnson-confluent** [abdullahkhawer/aws-auto-terminate-idle-emr#1]
This looks like a useful utility! Do you mind adding a license file to the project?

**Comment by abdullahkhawer** [comment]
Sure. Thanks for the suggestion. I'm glad you find it useful. I will surely add a license file shortly.

**Comment by abdullahkhawer** [comment]
I have added the LICENSE file.

You can see here: https://github.com/abdullahkhawer/aws-auto-terminate-idle-emr/blob/master/LICENSE
